name: "Enforce changelog"
on:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: julia-actions/setup-julia@fa02766e078afaaf09b14210362cee14137e6a32 # v3.0.2
        with:
          version: '1'
      - uses: dangoslen/changelog-enforcer@8b5e9dc3121363bb7c0115f8533404d92af382de # v3.7.0
        with:
          changeLogPath: 'CHANGELOG.md'
          skipLabels: 'skip-changelog'
      - run: julia --project=.ci -e 'using Pkg; Pkg.instantiate()'
      - run: julia --project=.ci .ci/changelog.jl
      - run: git diff --exit-code
